/**
 * Generates `public/skills/about/SKILL.md` — the agent skill artifact — from
 * `src/lib/me.ts`, and writes its SHA-256 digest to
 * `src/lib/skill-digest.gen.ts` so the agent-skills discovery index
 * (`src/lib/discovery.ts`) can advertise a digest that always matches the
 * artifact actually served.
 *
 * Runs automatically during `vite build` (the `generate-static-files` plugin
 * in `vite.config.ts`) and standalone via `node scripts/generate-skill.ts`.
 *
 * Relies on Node's native TypeScript type stripping to import `me.ts`
 * directly (Node 22.6+, default in Node 24 — the version pinned by `.nvmrc`).
 */
import { createHash } from 'node:crypto'
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { me } from '../src/lib/me.ts'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const skillOut = join(root, 'public', 'skills', 'about', 'SKILL.md')
const digestOut = join(root, 'src', 'lib', 'skill-digest.gen.ts')

/** Stable identifier for the skill (must match `agentSkillsIndex()`). */
const SKILL_NAME = 'about-zubair'

/** Friendlier display titles for the lowercase link labels in `me.links`. */
const linkTitles: Record<string, string> = {
	github: 'GitHub',
	x: 'X',
	linkedin: 'LinkedIn',
	email: 'Email',
	whatsapp: 'WhatsApp',
}

export function generateSkill(): { skillOut: string; digestOut: string } {
	const base = `https://${me.host}`

	const lines = [
		'---',
		`name: ${SKILL_NAME}`,
		`description: Facts about ${me.name} — role, current projects, and contact links.`,
		'---',
		'',
		`# About ${me.name}`,
		'',
		`- **Name:** ${me.name}`,
		`- **Role:** ${me.role}`,
		`- **Site:** ${base}`,
	]

	if (me.now.length > 0) {
		lines.push('', '## Current projects', '')
		for (const item of me.now) {
			lines.push(`- ${item.label} — ${item.href}`)
		}
	}

	if (me.links.length > 0) {
		lines.push('', '## Links', '')
		for (const link of me.links) {
			const title = linkTitles[link.label] ?? link.label
			lines.push(`- ${title}: ${link.href}`)
		}
	}

	const content = `${lines.join('\n')}\n`
	const digest = `sha256:${createHash('sha256').update(content).digest('hex')}`

	mkdirSync(dirname(skillOut), { recursive: true })
	writeFileSync(skillOut, content)

	mkdirSync(dirname(digestOut), { recursive: true })
	writeFileSync(
		digestOut,
		`// Generated by scripts/generate-skill.ts — do not edit by hand.\nexport const SKILL_DIGEST = '${digest}'\n`,
	)

	return { skillOut, digestOut }
}

// Standalone: `node scripts/generate-skill.ts`
if (
	process.argv[1] &&
	import.meta.url === pathToFileURL(process.argv[1]).href
) {
	const { skillOut, digestOut } = generateSkill()
	console.log(`generated ${skillOut}`)
	console.log(`generated ${digestOut}`)
}
